
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class PokemonKartları extends javax.swing.JFrame {

    /**
     * Creates new form PokemonKartları
     */
    Main m = new Main();
    Oyuncu oyuncu1 = null;
    Oyuncu oyuncu2 = null;
    int kullanici1SectigiKart;
    int kullanici2SectigiKart;
    int k1OynadiMi;
    int k2OynadiMi;
    String oyuncu2tip;

    public PokemonKartları() {
        initComponents();

        m.pokemonKartOlustur();
        m.PokemonOlustur();

        int tür;
        Object[] options = {
            "Bilgisayar-Bilgisayar",
            "Kullanıcı-Bilgisayar"};
        tür = JOptionPane.showOptionDialog(new JFrame(),
                "Oyuncu türünü seçiniz.",
                "",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[1]);
        if (tür == -1) {
            System.exit(0);
        }
        if (tür == 0) {

            oyuncu1 = new BilgisayarOyuncusu(1, "Bilgisayar1", 0);
            oyuncu2 = new BilgisayarOyuncusu(2, "Bilgisayar2", 0);
        } else if (tür == 1) {
            oyuncu1 = new BilgisayarOyuncusu(1, "Bilgisayar1", 0);
            oyuncu2 = new InsanOyuncusu(2, "Kullanıcı1", 0);

        }
        oyuncu2tip = String.valueOf(oyuncu2.getClass());
        m.kartAta(oyuncu1);
        m.kartAta(oyuncu2);

        k1kart1.setIcon(m.pokemonImages.get(10));
        k1kart2.setIcon(m.pokemonImages.get(10));
        k1kart3.setIcon(m.pokemonImages.get(10));
        k2kart1.setIcon(m.pokemonImages.get(10));
        k2kart2.setIcon(m.pokemonImages.get(10));
        k2kart3.setIcon(m.pokemonImages.get(10));
        deste.setIcon(m.pokemonImages.get(10));

        /* Main m=new Main();
      BilgisayarOyuncusu bilgisayar=new BilgisayarOyuncusu(26,"Batuhan",0);
       ImageIcon Icoon =new ImageIcon (new ImageIcon("kartlar/Pikachu.jpg").getImage().getScaledInstance(200,286,Image.SCALE_DEFAULT));
        m.pokemonKartOlustur();
        m.PokemonOlustur();
        k1kart1.setIcon(m.pokemonImages.get(0));
        System.out.println(m.pokemons.get(0).getPokemonAdi());
        m.kartAta(oyuncu1);
        for(int i=0;i<3;i++){
            System.out.println(bilgisayar.kartListesi[i][1]);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kullanıcı1 = new javax.swing.JLabel();
        kullanıcı2 = new javax.swing.JLabel();
        k1kart1 = new javax.swing.JLabel();
        k1kart2 = new javax.swing.JLabel();
        k1kart3 = new javax.swing.JLabel();
        k2kart1 = new javax.swing.JLabel();
        k2kart2 = new javax.swing.JLabel();
        k2kart3 = new javax.swing.JLabel();
        ortakart1 = new javax.swing.JLabel();
        ortakart2 = new javax.swing.JLabel();
        deste = new javax.swing.JLabel();
        kartlariAc1 = new javax.swing.JButton();
        kartAc = new javax.swing.JButton();
        kartlariAc2 = new javax.swing.JButton();
        oyuncu2scor = new javax.swing.JLabel();
        oyuncu1scor = new javax.swing.JLabel();
        kartAt = new javax.swing.JButton();
        destedenCek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Kullanıcı1.setText("Oyuncu1");

        kullanıcı2.setText("Oyuncu2");

        k1kart1.setText("k1kart1");

        k1kart2.setText("k1kart2");

        k1kart3.setText("k1kart3");

        k2kart1.setText("k2kart1");
        k2kart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                k2kart1MouseClicked(evt);
            }
        });

        k2kart2.setText("k2kart2");
        k2kart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                k2kart2MouseClicked(evt);
            }
        });

        k2kart3.setText("k2kart3");
        k2kart3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                k2kart3MouseClicked(evt);
            }
        });

        ortakart1.setText("orta1");

        ortakart2.setText("orta2");

        deste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deste.setText("deste");

        kartlariAc1.setText("Kartları Aç");
        kartlariAc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartlariAc1ActionPerformed(evt);
            }
        });

        kartAc.setText("Kart Aç");
        kartAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartAcActionPerformed(evt);
            }
        });

        kartlariAc2.setText("Kartları Aç");
        kartlariAc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartlariAc2ActionPerformed(evt);
            }
        });

        oyuncu2scor.setText("         oyuncu2scor");

        oyuncu1scor.setText("       oyuncu1scor");

        kartAt.setText("Kart At");
        kartAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kartAtActionPerformed(evt);
            }
        });

        destedenCek.setText("Desteden Cek");
        destedenCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destedenCekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(680, Short.MAX_VALUE)
                .addComponent(Kullanıcı1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(600, 600, 600))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(oyuncu1scor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(deste, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oyuncu2scor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destedenCek))))
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(k1kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k2kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullanıcı2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(k1kart2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107)
                                        .addComponent(k1kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(k2kart2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(k2kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(kartAt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kartlariAc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kartAc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kartlariAc2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(ortakart1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(ortakart2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Kullanıcı1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(k1kart2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(k1kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(k1kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kartlariAc1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kartAc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kartAt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(k2kart3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kartlariAc2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ortakart2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ortakart1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oyuncu1scor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(deste, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(destedenCek, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(k2kart1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oyuncu2scor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(k2kart2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(kullanıcı2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void k2kart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k2kart1MouseClicked
        if ((String.valueOf(oyuncu2.getClass()).equals("class InsanOyuncusu"))) {
            k2kart1.setIcon(m.pokemonImages.get(10));
            kullanici2SectigiKart = 0;
            ortakart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[kullanici2SectigiKart][0])));
            ortakart2.setIcon(m.pokemonImages.get(10));
        }

    }//GEN-LAST:event_k2kart1MouseClicked

    private void k2kart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k2kart2MouseClicked
        if (String.valueOf(oyuncu2.getClass()).equals("class InsanOyuncusu")) {
            k2kart2.setIcon(m.pokemonImages.get(10));
            kullanici2SectigiKart = 1;
            ortakart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[kullanici2SectigiKart][0])));
            ortakart2.setIcon(m.pokemonImages.get(10));
        }

    }//GEN-LAST:event_k2kart2MouseClicked

    private void k2kart3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_k2kart3MouseClicked
        if (String.valueOf(oyuncu2.getClass()).equals("class InsanOyuncusu")) {
            k2kart3.setIcon(m.pokemonImages.get(10));
            kullanici2SectigiKart = 2;
            ortakart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[kullanici2SectigiKart][0])));
            ortakart2.setIcon(m.pokemonImages.get(10));
        }

    }//GEN-LAST:event_k2kart3MouseClicked


    private void kartlariAc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartlariAc1ActionPerformed
        k1kart1.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu1.kartListesi[0][0])));
        k1kart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu1.kartListesi[1][0])));
        k1kart3.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu1.kartListesi[2][0])));

    }//GEN-LAST:event_kartlariAc1ActionPerformed

	    private void kartAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartAcActionPerformed

                ortakart1.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu1.kartListesi[kullanici1SectigiKart][0])));
                ortakart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[kullanici2SectigiKart][0])));
                if (m.pokemons.get(Integer.parseInt(oyuncu2.kartListesi[kullanici2SectigiKart][0])).hasarPuaniGoster() < m.pokemons.get(Integer.parseInt(oyuncu1.kartListesi[kullanici1SectigiKart][0])).hasarPuaniGoster()) {
                    oyuncu1.setSkor(oyuncu1.getSkor() + 5);
                } else if (m.pokemons.get(Integer.parseInt(oyuncu2.kartListesi[kullanici2SectigiKart][0])).hasarPuaniGoster() > m.pokemons.get(Integer.parseInt(oyuncu1.kartListesi[kullanici1SectigiKart][0])).hasarPuaniGoster()) {
                    oyuncu2.setSkor(oyuncu2.getSkor() + 5);
                }
                oyuncu1scor.setText("Oyuncu 1 skor : " + oyuncu1.getSkor());
                oyuncu2scor.setText("Oyuncu 2 skor : " + oyuncu2.getSkor());
                oyuncu1.kartListesi[kullanici1SectigiKart][0] = "26";
                oyuncu2.kartListesi[kullanici2SectigiKart][0] = "26";

                int tmp = 0;
                for (int i = 0; i < 3; i++) {

                    if (oyuncu1.kartListesi[i][0].equals("26") && oyuncu2.kartListesi[i][0].equals("26")) {  // 26 sayısı oyunu sonlandırmak için random atılan bir sayıdır.
                        tmp++;
                    }
                    if (tmp == 3) {
                        if (oyuncu1.getSkor() > oyuncu2.getSkor()) {
                            JOptionPane.showMessageDialog(null, "Tebrikler! Kazanan Oyuncu1");
                        }

                        if (oyuncu1.getSkor() < oyuncu2.getSkor()) {
                            JOptionPane.showMessageDialog(null, "Tebrikler! Kazanan Oyuncu2");
                        }

                        if (oyuncu1.getSkor() == oyuncu2.getSkor()) {
                            JOptionPane.showMessageDialog(null, "Oyun Berabere");
                        }
                        System.exit(0);
                    }
                }


    }//GEN-LAST:event_kartAcActionPerformed

    private void kartlariAc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartlariAc2ActionPerformed
        k2kart1.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[0][0])));
        k2kart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[1][0])));
        k2kart3.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[2][0])));
    }//GEN-LAST:event_kartlariAc2ActionPerformed

    private void kartAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kartAtActionPerformed

        kullanici1SectigiKart = oyuncu1.kartSec(oyuncu1);

        if (kullanici1SectigiKart == 0) {
            k1kart1.setIcon(m.pokemonImages.get(10));
        } else if (kullanici1SectigiKart == 1) {
            k1kart2.setIcon(m.pokemonImages.get(10));
        } else if (kullanici1SectigiKart == 2) {
            k1kart3.setIcon(m.pokemonImages.get(10));
        }
        if (oyuncu2tip.equals("class BilgisayarOyuncusu")) {

            kullanici2SectigiKart = oyuncu2.kartSec(oyuncu2);

        }

        if (kullanici2SectigiKart == 0) {
            k2kart1.setIcon(m.pokemonImages.get(10));
        } else if (kullanici2SectigiKart == 1) {
            k2kart2.setIcon(m.pokemonImages.get(10));
        } else if (kullanici2SectigiKart == 2) {
            k2kart3.setIcon(m.pokemonImages.get(10));
        }

        ortakart1.setIcon(m.pokemonImages.get(10));
        ortakart2.setIcon(m.pokemonImages.get(10));
       

    }//GEN-LAST:event_kartAtActionPerformed

    private void destedenCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destedenCekActionPerformed

        if (m.kullanılanKartlar.size() < 10) {
            m.destedenCek(oyuncu1, kullanici1SectigiKart);
            m.destedenCek(oyuncu2, kullanici2SectigiKart);
            k1kart1.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu1.kartListesi[0][0])));
            k1kart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu1.kartListesi[1][0])));
            k1kart3.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu1.kartListesi[2][0])));
            k2kart1.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[0][0])));
            k2kart2.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[1][0])));
            k2kart3.setIcon(m.pokemonImages.get(Integer.parseInt(oyuncu2.kartListesi[2][0])));
          
        }


    }//GEN-LAST:event_destedenCekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonKartları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonKartları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonKartları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonKartları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonKartları().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kullanıcı1;
    private javax.swing.JLabel deste;
    private javax.swing.JButton destedenCek;
    private javax.swing.JLabel k1kart1;
    private javax.swing.JLabel k1kart2;
    private javax.swing.JLabel k1kart3;
    private javax.swing.JLabel k2kart1;
    private javax.swing.JLabel k2kart2;
    private javax.swing.JLabel k2kart3;
    private javax.swing.JButton kartAc;
    private javax.swing.JButton kartAt;
    private javax.swing.JButton kartlariAc1;
    private javax.swing.JButton kartlariAc2;
    private javax.swing.JLabel kullanıcı2;
    private javax.swing.JLabel ortakart1;
    private javax.swing.JLabel ortakart2;
    private javax.swing.JLabel oyuncu1scor;
    private javax.swing.JLabel oyuncu2scor;
    // End of variables declaration//GEN-END:variables
}
